// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Smart_Gadget

// esp-brookesia: changed-删了#include "ui_helpers.h"
#include "ui.h"


// esp-brookesia: changed
//这个宏让你用统一的方式切换 LVGL 屏幕，并带有动画效果。实际调用时，只需写 _ui_screen_change(...)，就能实现带动画的屏幕切换。
#if !defined(ESP_BROOKESIA_SQ1_4_1_LV8_3_11)
#define _ui_screen_change(target, fademode, spd, delay, target_init) lv_scr_load_anim(*target, fademode, spd, delay, false)
#endif
///////////////////// VARIABLES ////////////////////
void upanim_Animation(lv_obj_t * TargetObject, int delay);
void hour_Animation(lv_obj_t * TargetObject, int delay);
void min_Animation(lv_obj_t * TargetObject, int delay);
void sec_Animation(lv_obj_t * TargetObject, int delay);
void scrolldot_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Screen_Splash
void ui_Screen_Splash_screen_init(void);
void ui_event_Screen_Splash(lv_event_t * e);
lv_obj_t * ui_Screen_Splash;
lv_obj_t * ui_Splash_Small_Label_Demo;
lv_obj_t * ui_Splash_Small_Label_Smart_Gadget;
lv_obj_t * ui_Splash_Image_SLS_Logo;
// CUSTOM VARIABLES


// SCREEN: ui_Screen_Clock
void ui_Screen_Clock_screen_init(void);
void ui_event_Screen_Clock(lv_event_t * e);
lv_obj_t * ui_Screen_Clock;
lv_obj_t * ui_Clock_Panel_Clock_Panel;
lv_obj_t * ui_Clock_Clock_Dot_Dot1;
lv_obj_t * ui_Clock_Clock_Dot_Dot2;
lv_obj_t * ui_Clock_Clock_Dot_Dot3;
lv_obj_t * ui_Clock_Clock_Dot_Dot4;
lv_obj_t * ui_Clock_Clock_Dot_Dot5;
lv_obj_t * ui_Clock_Clock_Dot_Dot6;
lv_obj_t * ui_Clock_Clock_Dot_Dot7;
lv_obj_t * ui_Clock_Clock_Dot_Dot8;
lv_obj_t * ui_Clock_Small_Label_Clock_Number1;
lv_obj_t * ui_Clock_Small_Label_Clock_Number2;
lv_obj_t * ui_Clock_Small_Label_Clock_Number3;
lv_obj_t * ui_Clock_Small_Label_Clock_Number4;
lv_obj_t * ui_Clock_Image_Min;
lv_obj_t * ui_Clock_Image_Hour;
lv_obj_t * ui_Clock_Image_Sec;
lv_obj_t * ui_Clock_Panel_Clock_Center;
lv_obj_t * ui_Clock_Label_Clock_Number;
lv_obj_t * ui_Clock_Small_Label_Date;
lv_obj_t * ui_Clock_Scrolldots_Scrolldots;
// CUSTOM VARIABLES


// SCREEN: ui_Screen_Call
void ui_Screen_Call_screen_init(void);
void ui_event_Screen_Call(lv_event_t * e);
lv_obj_t * ui_Screen_Call;
lv_obj_t * ui_Call_Small_Label_Elena;
lv_obj_t * ui_Call_Small_Label_Incoming;
lv_obj_t * ui_Call_Panel_Call_Incon1;
lv_obj_t * ui_Call_Image_Phone1;
lv_obj_t * ui_Call_Panel_Call_Incon2;
lv_obj_t * ui_Call_Image_Phone2;
lv_obj_t * ui_Call_Image_Avatar;
lv_obj_t * ui_Call_Scrolldots_Scrolldots1;
// CUSTOM VARIABLES


// SCREEN: ui_Screen_Chat
void ui_Screen_Chat_screen_init(void);
void ui_event_Screen_Chat(lv_event_t * e);
lv_obj_t * ui_Screen_Chat;
lv_obj_t * ui_Chat_Panel_Chat_container;
lv_obj_t * ui_Chat_Small_Label_Chat_date;
lv_obj_t * ui_Chat_Panel_C1;
lv_obj_t * ui_Chat_Panel_Chat_Panel1;
lv_obj_t * ui_Chat_Small_Label_Chat1;
lv_obj_t * ui_Chat_Image_Chat_Icon1;
lv_obj_t * ui_Chat_Panel_C2;
lv_obj_t * ui_Chat_Panel_Chat_Panel2;
lv_obj_t * ui_Chat_Small_Label_Chat2;
lv_obj_t * ui_Chat_Image_Chat_Icon2;
lv_obj_t * ui_Chat_Small_Label_Delifered;
lv_obj_t * ui_Chat_Panel_C3;
lv_obj_t * ui_Chat_Panel_Chat_Panel3;
lv_obj_t * ui_Chat_Small_Label_Chat3;
lv_obj_t * ui_Chat_Image_Chat_Icon3;
lv_obj_t * ui_Chat_Scrolldots_Scrolldots2;
// CUSTOM VARIABLES


// SCREEN: ui_Screen_Music_Player
void ui_Screen_Music_Player_screen_init(void);
void ui_event_Screen_Music_Player(lv_event_t * e);
lv_obj_t * ui_Screen_Music_Player;
lv_obj_t * ui_Music_Player_Small_Label_Music_Title;
lv_obj_t * ui_Music_Player_Small_Label_Author;
lv_obj_t * ui_Music_Player_Panel_Play_btn;
lv_obj_t * ui_Music_Player_Image_Play;
lv_obj_t * ui_Music_Player_Image_Album;
lv_obj_t * ui_Music_Player_Image_Backward;
lv_obj_t * ui_Music_Player_Image_Forward;
lv_obj_t * ui_Music_Player_Scrolldots_Scrolldots3;
// CUSTOM VARIABLES


// SCREEN: ui_Screen_Weather
void ui_Screen_Weather_screen_init(void);
void ui_event_Screen_Weather(lv_event_t * e);
lv_obj_t * ui_Screen_Weather;
lv_obj_t * ui_Weather_Small_Label_Pary_Cloud;
lv_obj_t * ui_Weather_Small_Label_New_York;
lv_obj_t * ui_Weather_Image_Cloud;
lv_obj_t * ui_Weather_Label_Celsius;
lv_obj_t * ui_Weather_Panel_Weather_Icons;
lv_obj_t * ui_Weather_Image_w1;
lv_obj_t * ui_Weather_Image_w2;
lv_obj_t * ui_Weather_Image_w3;
lv_obj_t * ui_Weather_Small_Label_W1_Num;
lv_obj_t * ui_Weather_Small_Label_W2_Num;
lv_obj_t * ui_Weather_Small_Label_W3_Num;
lv_obj_t * ui_Weather_Scrolldots_Scrolldots4;
// CUSTOM VARIABLES


// SCREEN: ui_Screen_Alarm
void ui_Screen_Alarm_screen_init(void);
void ui_event_Screen_Alarm(lv_event_t * e);
lv_obj_t * ui_Screen_Alarm;
lv_obj_t * ui_Alarm_Panel_Alarm_container;
lv_obj_t * ui_Alarm_Small_Label_Set_alarm;
lv_obj_t * ui_Alarm_Alarm_Comp_Alarm_Comp;
lv_obj_t * ui_Alarm_Alarm_Comp_Alarm_Comp1;
lv_obj_t * ui_Alarm_Alarm_Comp_Alarm_Comp2;
lv_obj_t * ui_Alarm_Alarm_Comp_Alarm_Comp3;
lv_obj_t * ui_Alarm_Scrolldots_Scrolldots5;
// CUSTOM VARIABLES

// EVENTS
void ui_event_Startevents____initial_actions0(lv_event_t * e);
lv_obj_t * ui_Startevents____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_image_dsc_t * ui_imgset_chatbox[1] = {&ui_img_chatbox2_png};
const lv_image_dsc_t * ui_imgset_weather_[3] = {&ui_img_weather_1_png, &ui_img_weather_2_png, &ui_img_weather_3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
//esp-brookesia: changed-把这一段移出去了
void upanim_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -30, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 100);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, true);
    lv_anim_start(&PropertyAnimation_1);

}
void hour_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 2800);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 300);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, true);
    lv_anim_start(&PropertyAnimation_1);

}
void min_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 2100);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 200);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, true);
    lv_anim_start(&PropertyAnimation_1);

}
void sec_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 600);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 3600);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 1000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, true);
    lv_anim_start(&PropertyAnimation_1);

}
void scrolldot_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 30, -8);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen_Splash(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_Splash_Image_SLS_Logo, 100);
        upanim_Animation(ui_Splash_Small_Label_Smart_Gadget, 200);
        upanim_Animation(ui_Splash_Small_Label_Demo, 300);
        _ui_screen_change(&ui_Screen_Clock, LV_SCR_LOAD_ANIM_FADE_ON, 200, 1400, &ui_Screen_Clock_screen_init);
    }
}

void ui_event_Screen_Clock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        upanim_Animation(ui_Clock_Panel_Clock_Panel, 100);
        upanim_Animation(ui_Clock_Label_Clock_Number, 300);
        upanim_Animation(ui_Clock_Small_Label_Date, 200);
        scrolldot_Animation(ui_Clock_Scrolldots_Scrolldots, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen_Call, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Screen_Call_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen_Alarm, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen_Alarm_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        hour_Animation(ui_Clock_Image_Hour, 200);
        min_Animation(ui_Clock_Image_Min, 400);
    }
}

void ui_event_Screen_Call(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_Call_Image_Avatar, 100);
        upanim_Animation(ui_Call_Small_Label_Elena, 200);
        upanim_Animation(ui_Call_Small_Label_Incoming, 300);
        upanim_Animation(ui_Call_Panel_Call_Incon1, 200);
        upanim_Animation(ui_Call_Panel_Call_Incon2, 300);
        scrolldot_Animation(ui_Call_Scrolldots_Scrolldots1, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen_Chat, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen_Chat_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen_Clock, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen_Clock_screen_init);
    }
}

void ui_event_Screen_Chat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_Chat_Small_Label_Chat_date, 100);
        upanim_Animation(ui_Chat_Panel_C1, 200);
        upanim_Animation(ui_Chat_Panel_C2, 300);
        upanim_Animation(ui_Chat_Panel_C3, 400);
        scrolldot_Animation(ui_Chat_Scrolldots_Scrolldots2, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen_Call, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen_Call_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen_Music_Player, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen_Music_Player_screen_init);
    }
}

void ui_event_Screen_Music_Player(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_Music_Player_Image_Album, 100);
        upanim_Animation(ui_Music_Player_Small_Label_Music_Title, 200);
        upanim_Animation(ui_Music_Player_Small_Label_Author, 300);
        upanim_Animation(ui_Music_Player_Panel_Play_btn, 200);
        upanim_Animation(ui_Music_Player_Image_Forward, 300);
        upanim_Animation(ui_Music_Player_Image_Backward, 400);
        scrolldot_Animation(ui_Music_Player_Scrolldots_Scrolldots3, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen_Chat, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen_Chat_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen_Weather, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen_Weather_screen_init);
    }
}

void ui_event_Screen_Weather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_Weather_Image_Cloud, 100);
        upanim_Animation(ui_Weather_Small_Label_Pary_Cloud, 200);
        upanim_Animation(ui_Weather_Label_Celsius, 300);
        upanim_Animation(ui_Weather_Small_Label_New_York, 400);
        upanim_Animation(ui_Weather_Panel_Weather_Icons, 300);
        scrolldot_Animation(ui_Weather_Scrolldots_Scrolldots4, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen_Music_Player, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen_Music_Player_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen_Alarm, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen_Alarm_screen_init);
    }
}

void ui_event_Screen_Alarm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_Alarm_Small_Label_Set_alarm, 100);
        upanim_Animation(ui_Alarm_Alarm_Comp_Alarm_Comp, 200);
        upanim_Animation(ui_Alarm_Alarm_Comp_Alarm_Comp1, 300);
        upanim_Animation(ui_Alarm_Alarm_Comp_Alarm_Comp2, 400);
        upanim_Animation(ui_Alarm_Alarm_Comp_Alarm_Comp3, 500);
        scrolldot_Animation(ui_Alarm_Scrolldots_Scrolldots5, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen_Weather, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen_Weather_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen_Clock, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen_Clock_screen_init);
    }
}

void ui_event_Startevents____initial_actions0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        sec_Animation(ui_Clock_Image_Sec, 0);
    }
}

///////////////////// SCREENS ////////////////////
// esp-brookesia: changed-改了名称
void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_simple_init(dispp);
    lv_disp_set_theme(dispp, theme);
    ui_Screen_Splash_screen_init();
    ui_Screen_Clock_screen_init();
    ui_Screen_Call_screen_init();
    ui_Screen_Chat_screen_init();
    ui_Screen_Music_Player_screen_init();
    ui_Screen_Weather_screen_init();
    ui_Screen_Alarm_screen_init();
    ui_Startevents____initial_actions0 = lv_obj_create(NULL);
    lv_obj_add_event_cb(ui_Startevents____initial_actions0, ui_event_Startevents____initial_actions0, LV_EVENT_ALL, NULL);
    lv_disp_load_scr(ui_Screen_Splash);
}
