// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Smart_Gadget

#ifndef _SMART_GADGET_UI_H
#define _SMART_GADGET_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "esp_brookesia.h"

#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void upanim_Animation(lv_obj_t * TargetObject, int delay);
void hour_Animation(lv_obj_t * TargetObject, int delay);
void min_Animation(lv_obj_t * TargetObject, int delay);
void sec_Animation(lv_obj_t * TargetObject, int delay);
void scrolldot_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen_Splash
void ui_Screen_Splash_screen_init(void);
void ui_event_Screen_Splash(lv_event_t * e);
extern lv_obj_t * ui_Screen_Splash;
extern lv_obj_t * ui_Splash_Small_Label_Demo;
extern lv_obj_t * ui_Splash_Small_Label_Smart_Gadget;
extern lv_obj_t * ui_Splash_Image_SLS_Logo;
// CUSTOM VARIABLES

// SCREEN: ui_Screen_Clock
void ui_Screen_Clock_screen_init(void);
void ui_event_Screen_Clock(lv_event_t * e);
extern lv_obj_t * ui_Screen_Clock;
extern lv_obj_t * ui_Clock_Panel_Clock_Panel;
extern lv_obj_t * ui_Clock_Clock_Dot_Dot1;
extern lv_obj_t * ui_Clock_Clock_Dot_Dot2;
extern lv_obj_t * ui_Clock_Clock_Dot_Dot3;
extern lv_obj_t * ui_Clock_Clock_Dot_Dot4;
extern lv_obj_t * ui_Clock_Clock_Dot_Dot5;
extern lv_obj_t * ui_Clock_Clock_Dot_Dot6;
extern lv_obj_t * ui_Clock_Clock_Dot_Dot7;
extern lv_obj_t * ui_Clock_Clock_Dot_Dot8;
extern lv_obj_t * ui_Clock_Small_Label_Clock_Number1;
extern lv_obj_t * ui_Clock_Small_Label_Clock_Number2;
extern lv_obj_t * ui_Clock_Small_Label_Clock_Number3;
extern lv_obj_t * ui_Clock_Small_Label_Clock_Number4;
extern lv_obj_t * ui_Clock_Image_Min;
extern lv_obj_t * ui_Clock_Image_Hour;
extern lv_obj_t * ui_Clock_Image_Sec;
extern lv_obj_t * ui_Clock_Panel_Clock_Center;
extern lv_obj_t * ui_Clock_Label_Clock_Number;
extern lv_obj_t * ui_Clock_Small_Label_Date;
extern lv_obj_t * ui_Clock_Scrolldots_Scrolldots;
// CUSTOM VARIABLES

// SCREEN: ui_Screen_Call
void ui_Screen_Call_screen_init(void);
void ui_event_Screen_Call(lv_event_t * e);
extern lv_obj_t * ui_Screen_Call;
extern lv_obj_t * ui_Call_Small_Label_Elena;
extern lv_obj_t * ui_Call_Small_Label_Incoming;
extern lv_obj_t * ui_Call_Panel_Call_Incon1;
extern lv_obj_t * ui_Call_Image_Phone1;
extern lv_obj_t * ui_Call_Panel_Call_Incon2;
extern lv_obj_t * ui_Call_Image_Phone2;
extern lv_obj_t * ui_Call_Image_Avatar;
extern lv_obj_t * ui_Call_Scrolldots_Scrolldots1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen_Chat
void ui_Screen_Chat_screen_init(void);
void ui_event_Screen_Chat(lv_event_t * e);
extern lv_obj_t * ui_Screen_Chat;
extern lv_obj_t * ui_Chat_Panel_Chat_container;
extern lv_obj_t * ui_Chat_Small_Label_Chat_date;
extern lv_obj_t * ui_Chat_Panel_C1;
extern lv_obj_t * ui_Chat_Panel_Chat_Panel1;
extern lv_obj_t * ui_Chat_Small_Label_Chat1;
extern lv_obj_t * ui_Chat_Image_Chat_Icon1;
extern lv_obj_t * ui_Chat_Panel_C2;
extern lv_obj_t * ui_Chat_Panel_Chat_Panel2;
extern lv_obj_t * ui_Chat_Small_Label_Chat2;
extern lv_obj_t * ui_Chat_Image_Chat_Icon2;
extern lv_obj_t * ui_Chat_Small_Label_Delifered;
extern lv_obj_t * ui_Chat_Panel_C3;
extern lv_obj_t * ui_Chat_Panel_Chat_Panel3;
extern lv_obj_t * ui_Chat_Small_Label_Chat3;
extern lv_obj_t * ui_Chat_Image_Chat_Icon3;
extern lv_obj_t * ui_Chat_Scrolldots_Scrolldots2;
// CUSTOM VARIABLES

// SCREEN: ui_Screen_Music_Player
void ui_Screen_Music_Player_screen_init(void);
void ui_event_Screen_Music_Player(lv_event_t * e);
extern lv_obj_t * ui_Screen_Music_Player;
extern lv_obj_t * ui_Music_Player_Small_Label_Music_Title;
extern lv_obj_t * ui_Music_Player_Small_Label_Author;
extern lv_obj_t * ui_Music_Player_Panel_Play_btn;
extern lv_obj_t * ui_Music_Player_Image_Play;
extern lv_obj_t * ui_Music_Player_Image_Album;
extern lv_obj_t * ui_Music_Player_Image_Backward;
extern lv_obj_t * ui_Music_Player_Image_Forward;
extern lv_obj_t * ui_Music_Player_Scrolldots_Scrolldots3;
// CUSTOM VARIABLES

// SCREEN: ui_Screen_Weather
void ui_Screen_Weather_screen_init(void);
void ui_event_Screen_Weather(lv_event_t * e);
extern lv_obj_t * ui_Screen_Weather;
extern lv_obj_t * ui_Weather_Small_Label_Pary_Cloud;
extern lv_obj_t * ui_Weather_Small_Label_New_York;
extern lv_obj_t * ui_Weather_Image_Cloud;
extern lv_obj_t * ui_Weather_Label_Celsius;
extern lv_obj_t * ui_Weather_Panel_Weather_Icons;
extern lv_obj_t * ui_Weather_Image_w1;
extern lv_obj_t * ui_Weather_Image_w2;
extern lv_obj_t * ui_Weather_Image_w3;
extern lv_obj_t * ui_Weather_Small_Label_W1_Num;
extern lv_obj_t * ui_Weather_Small_Label_W2_Num;
extern lv_obj_t * ui_Weather_Small_Label_W3_Num;
extern lv_obj_t * ui_Weather_Scrolldots_Scrolldots4;
// CUSTOM VARIABLES

// SCREEN: ui_Screen_Alarm
void ui_Screen_Alarm_screen_init(void);
void ui_event_Screen_Alarm(lv_event_t * e);
extern lv_obj_t * ui_Screen_Alarm;
extern lv_obj_t * ui_Alarm_Panel_Alarm_container;
extern lv_obj_t * ui_Alarm_Small_Label_Set_alarm;
extern lv_obj_t * ui_Alarm_Alarm_Comp_Alarm_Comp;
extern lv_obj_t * ui_Alarm_Alarm_Comp_Alarm_Comp1;
extern lv_obj_t * ui_Alarm_Alarm_Comp_Alarm_Comp2;
extern lv_obj_t * ui_Alarm_Alarm_Comp_Alarm_Comp3;
extern lv_obj_t * ui_Alarm_Scrolldots_Scrolldots5;
// CUSTOM VARIABLES

// EVENTS

void ui_event_Startevents____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui_Startevents____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_sls_logo_png);    // assets/sls_logo.png
LV_IMG_DECLARE(ui_img_pattern_png);    // assets/pattern.png
LV_IMG_DECLARE(ui_img_clock_min_png);    // assets/clock_min.png
LV_IMG_DECLARE(ui_img_clock_hour_png);    // assets/clock_hour.png
LV_IMG_DECLARE(ui_img_clock_sec_png);    // assets/clock_sec.png
LV_IMG_DECLARE(ui_img_phone_png);    // assets/phone.png
LV_IMG_DECLARE(ui_img_avatar_png);    // assets/avatar.png
LV_IMG_DECLARE(ui_img_chatbox_png);    // assets/chatbox.png
LV_IMG_DECLARE(ui_img_chatbox2_png);    // assets/chatbox2.png
LV_IMG_DECLARE(ui_img_play_png);    // assets/play.png
LV_IMG_DECLARE(ui_img_album_png);    // assets/album.png
LV_IMG_DECLARE(ui_img_backward_png);    // assets/backward.png
LV_IMG_DECLARE(ui_img_forward_png);    // assets/forward.png
LV_IMG_DECLARE(ui_img_cloud_png);    // assets/cloud.png
LV_IMG_DECLARE(ui_img_weather_1_png);    // assets/weather_1.png
LV_IMG_DECLARE(ui_img_weather_2_png);    // assets/weather_2.png
LV_IMG_DECLARE(ui_img_weather_3_png);    // assets/weather_3.png

// FONTS
LV_FONT_DECLARE(ui_font_Number);

// UI INIT
// esp-brookesia: changed
void phone_app_squareline_jerry_ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
