// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen_Screen3_screen_init(void)
{
    ui_Screen_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen_Screen3, &ui_img_3_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Screen_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen_Screen3, ui_event_Screen_Screen3, LV_EVENT_ALL, NULL);

}
