// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen_Screen3_screen_init(void)
{
    ui_Screen_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen_Screen3, &ui_img_3_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Screen_Screen3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 确保对象可以接收点击事件
    lv_obj_add_flag(ui_Screen_Screen3, LV_OBJ_FLAG_CLICKABLE);
    
    // 添加更具体的事件监听，而不是 LV_EVENT_ALL
    lv_obj_add_event_cb(ui_Screen_Screen3, ui_event_Screen_Screen3, LV_EVENT_CLICKED, NULL);// 添加点击事件监听，用户完成一次完整的点击操作（按下并释放）
    lv_obj_add_event_cb(ui_Screen_Screen3, ui_event_Screen_Screen3, LV_EVENT_GESTURE, NULL);// 添加手势事件监听，用户进行手势操作（如滑动、拖拽）
    // lv_obj_add_event_cb(ui_Screen_Screen3, ui_event_Screen_Screen3, LV_EVENT_PRESSED, NULL);// 添加按下事件监听
    // lv_obj_add_event_cb(ui_Screen_Screen3, ui_event_Screen_Screen3, LV_EVENT_RELEASED, NULL);// 添加释放事件监听，用户松开屏幕的瞬间

}
