// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen_Screen2_screen_init(void)
{
    ui_Screen_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen_Screen2, &ui_img_2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Screen_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 确保对象可以接收点击事件
    lv_obj_add_flag(ui_Screen_Screen2, LV_OBJ_FLAG_CLICKABLE);
    
    // 添加更具体的事件监听，而不是 LV_EVENT_ALL
    lv_obj_add_event_cb(ui_Screen_Screen2, ui_event_Screen_Screen2, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_Screen_Screen2, ui_event_Screen_Screen2, LV_EVENT_GESTURE, NULL);
    lv_obj_add_event_cb(ui_Screen_Screen2, ui_event_Screen_Screen2, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(ui_Screen_Screen2, ui_event_Screen_Screen2, LV_EVENT_RELEASED, NULL);

}
