// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen_Screen1
void ui_Screen_Screen1_screen_init(void);
void ui_event_Screen_Screen1(lv_event_t * e);
lv_obj_t * ui_Screen_Screen1;
// CUSTOM VARIABLES


// SCREEN: ui_Screen_Screen2
void ui_Screen_Screen2_screen_init(void);
void ui_event_Screen_Screen2(lv_event_t * e);
lv_obj_t * ui_Screen_Screen2;
// CUSTOM VARIABLES


// SCREEN: ui_Screen_Screen3
void ui_Screen_Screen3_screen_init(void);
void ui_event_Screen_Screen3(lv_event_t * e);
lv_obj_t * ui_Screen_Screen3;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui_Startevents____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_image_dsc_t * ui_imgset_[3] = {&ui_img_1_png, &ui_img_2_png, &ui_img_3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen_Screen2_screen_init);
    }
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        player_1(e);
    }
}

void ui_event_Screen_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_Screen3_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_Screen1_screen_init);
        player_2(e);
    }
}

void ui_event_Screen_Screen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen_Screen2_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        player_3(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen_Screen1_screen_init();
    ui_Screen_Screen2_screen_init();
    ui_Screen_Screen3_screen_init();
    ui_Startevents____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen_Screen1);
}
