// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

// #include "ui_helpers.h"
#include "esp_brookesia.h"
#include "ui_events.h"

// SCREEN: ui_Screen_Screen1
void ui_Screen_Screen1_screen_init(void);
void ui_event_Screen_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen_Screen1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen_Screen2
void ui_Screen_Screen2_screen_init(void);
void ui_event_Screen_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen_Screen2;
// CUSTOM VARIABLES

// SCREEN: ui_Screen_Screen3
void ui_Screen_Screen3_screen_init(void);
void ui_event_Screen_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen_Screen3;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui_Startevents____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1_png);    // assets/1.png
LV_IMG_DECLARE(ui_img_2_png);    // assets/2.png
LV_IMG_DECLARE(ui_img_3_png);    // assets/3.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_mi);
LV_FONT_DECLARE(ui_font_zhinengxiyanqi);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
