// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H
#include "../decode.h"


#ifdef __cplusplus
extern "C" {
#endif

void player_1(lv_event_t * e);
void player_2(lv_event_t * e);
void player_3(lv_event_t * e);

// 播放器模块管理函数
void player_module_init(void);
void player_module_cleanup(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
