// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void player_1(lv_event_t * e)
{
	// Your code here
}

void player_2(lv_event_t * e)
{
	// Your code here
}

void player_3(lv_event_t * e)
{
	// Your code here
}
