// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Smart_Gadget

#ifndef _UI_COMP__H
#define _UI_COMP__H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
void get_component_child_event_cb(lv_event_t * e);
//声明一个事件回调函数，用于处理“获取组件子对象”相关的事件。参数 e 是 LVGL 事件结构体指针。
void del_component_child_event_cb(lv_event_t * e);
//声明一个事件回调函数，用于处理“删除组件子对象”相关的事件。参数同上。
lv_obj_t * ui_comp_get_child(lv_obj_t * comp, uint32_t child_idx);
//声明一个函数，用于根据索引 child_idx 获取指定组件 comp 的子对象，返回值是 LVGL 对象指针。
extern uint32_t LV_EVENT_GET_COMP_CHILD;
//声明一个外部变量，通常用于标识“获取组件子对象”事件的事件类型编号，供事件系统识别和使用。
*/

#include "ui_comp_alarm_comp.h"
#include "ui_comp_clock_dot.h"
#include "ui_comp_scrolldots.h"
#include "ui_comp_small_label.h"

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
