// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Smart_Gadget

#include "../ui.h"

void ui_Screen_Weather_screen_init(void)
{
    ui_Screen_Weather = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_Weather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Screen_Weather, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_Screen_Weather, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Small_Label_Pary_Cloud = ui_Label_Small_Label_create(ui_Screen_Weather);
    lv_obj_set_x(ui_Weather_Small_Label_Pary_Cloud, 0);
    lv_obj_set_y(ui_Weather_Small_Label_Pary_Cloud, -67);
    lv_obj_set_align(ui_Weather_Small_Label_Pary_Cloud, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Small_Label_Pary_Cloud, "Partly cloudy");
    lv_obj_set_style_text_color(ui_Weather_Small_Label_Pary_Cloud, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Small_Label_Pary_Cloud, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Small_Label_New_York = ui_Label_Small_Label_create(ui_Screen_Weather);
    lv_obj_set_x(ui_Weather_Small_Label_New_York, 0);
    lv_obj_set_y(ui_Weather_Small_Label_New_York, 37);
    lv_obj_set_align(ui_Weather_Small_Label_New_York, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather_Small_Label_New_York, "New York");
    lv_obj_set_style_text_color(ui_Weather_Small_Label_New_York, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Small_Label_New_York, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Image_Cloud = lv_image_create(ui_Screen_Weather);
    lv_image_set_src(ui_Weather_Image_Cloud, &ui_img_cloud_png);
    lv_obj_set_width(ui_Weather_Image_Cloud, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Image_Cloud, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Image_Cloud, -2);
    lv_obj_set_y(ui_Weather_Image_Cloud, 19);
    lv_obj_set_align(ui_Weather_Image_Cloud, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Weather_Image_Cloud, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Weather_Image_Cloud, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_Weather_Image_Cloud, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Weather_Image_Cloud, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Label_Celsius = lv_label_create(ui_Screen_Weather);
    lv_obj_set_width(ui_Weather_Label_Celsius, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Label_Celsius, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Label_Celsius, 0);
    lv_obj_set_y(ui_Weather_Label_Celsius, 125);
    lv_obj_set_align(ui_Weather_Label_Celsius, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Weather_Label_Celsius, "26°");
    lv_obj_set_style_text_color(ui_Weather_Label_Celsius, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Weather_Label_Celsius, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Weather_Label_Celsius, &ui_font_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Panel_Weather_Icons = lv_obj_create(ui_Screen_Weather);
    lv_obj_set_height(ui_Weather_Panel_Weather_Icons, 56);
    lv_obj_set_width(ui_Weather_Panel_Weather_Icons, lv_pct(100));
    lv_obj_set_x(ui_Weather_Panel_Weather_Icons, 0);
    lv_obj_set_y(ui_Weather_Panel_Weather_Icons, -33);
    lv_obj_set_align(ui_Weather_Panel_Weather_Icons, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Weather_Panel_Weather_Icons, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Weather_Panel_Weather_Icons, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Weather_Panel_Weather_Icons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Image_w1 = lv_image_create(ui_Weather_Panel_Weather_Icons);
    lv_image_set_src(ui_Weather_Image_w1, &ui_img_weather_1_png);
    lv_obj_set_width(ui_Weather_Image_w1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Image_w1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Image_w1, 40);
    lv_obj_set_y(ui_Weather_Image_w1, 0);
    lv_obj_add_flag(ui_Weather_Image_w1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Weather_Image_w1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_Weather_Image_w1, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Weather_Image_w1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Image_w2 = lv_image_create(ui_Weather_Panel_Weather_Icons);
    lv_image_set_src(ui_Weather_Image_w2, &ui_img_weather_2_png);
    lv_obj_set_width(ui_Weather_Image_w2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Image_w2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Weather_Image_w2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Weather_Image_w2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Weather_Image_w2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_Weather_Image_w2, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Weather_Image_w2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Image_w3 = lv_image_create(ui_Weather_Panel_Weather_Icons);
    lv_image_set_src(ui_Weather_Image_w3, &ui_img_weather_3_png);
    lv_obj_set_width(ui_Weather_Image_w3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather_Image_w3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather_Image_w3, -40);
    lv_obj_set_y(ui_Weather_Image_w3, 0);
    lv_obj_set_align(ui_Weather_Image_w3, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Weather_Image_w3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Weather_Image_w3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_Weather_Image_w3, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Weather_Image_w3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather_Small_Label_W1_Num = ui_Label_Small_Label_create(ui_Weather_Panel_Weather_Icons);
    lv_obj_set_x(ui_Weather_Small_Label_W1_Num, 35);
    lv_obj_set_y(ui_Weather_Small_Label_W1_Num, 25);
    lv_obj_set_align(ui_Weather_Small_Label_W1_Num, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_Weather_Small_Label_W1_Num, "65°");

    ui_Weather_Small_Label_W2_Num = ui_Label_Small_Label_create(ui_Weather_Panel_Weather_Icons);
    lv_obj_set_x(ui_Weather_Small_Label_W2_Num, 0);
    lv_obj_set_y(ui_Weather_Small_Label_W2_Num, 25);
    lv_obj_set_align(ui_Weather_Small_Label_W2_Num, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Weather_Small_Label_W2_Num, "24km/h");

    ui_Weather_Small_Label_W3_Num = ui_Label_Small_Label_create(ui_Weather_Panel_Weather_Icons);
    lv_obj_set_x(ui_Weather_Small_Label_W3_Num, -30);
    lv_obj_set_y(ui_Weather_Small_Label_W3_Num, 25);
    lv_obj_set_align(ui_Weather_Small_Label_W3_Num, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Weather_Small_Label_W3_Num, "18%");

    ui_Weather_Scrolldots_Scrolldots4 = ui_Panel_Scrolldots_create(ui_Screen_Weather);
    lv_obj_set_x(ui_Weather_Scrolldots_Scrolldots4, 0);
    lv_obj_set_y(ui_Weather_Scrolldots_Scrolldots4, -8);

    lv_obj_set_width(ui_comp_get_child(ui_Weather_Scrolldots_Scrolldots4, UI_COMP_PANEL_SCROLLDOTS_PANEL_D1), 4);
    lv_obj_set_height(ui_comp_get_child(ui_Weather_Scrolldots_Scrolldots4, UI_COMP_PANEL_SCROLLDOTS_PANEL_D1), 4);

    lv_obj_set_x(ui_comp_get_child(ui_Weather_Scrolldots_Scrolldots4, UI_COMP_PANEL_SCROLLDOTS_PANEL_D2), 10);
    lv_obj_set_y(ui_comp_get_child(ui_Weather_Scrolldots_Scrolldots4, UI_COMP_PANEL_SCROLLDOTS_PANEL_D2), 0);

    lv_obj_set_x(ui_comp_get_child(ui_Weather_Scrolldots_Scrolldots4, UI_COMP_PANEL_SCROLLDOTS_PANEL_D3), 20);
    lv_obj_set_y(ui_comp_get_child(ui_Weather_Scrolldots_Scrolldots4, UI_COMP_PANEL_SCROLLDOTS_PANEL_D3), 0);

    lv_obj_set_x(ui_comp_get_child(ui_Weather_Scrolldots_Scrolldots4, UI_COMP_PANEL_SCROLLDOTS_PANEL_D4), 30);
    lv_obj_set_y(ui_comp_get_child(ui_Weather_Scrolldots_Scrolldots4, UI_COMP_PANEL_SCROLLDOTS_PANEL_D4), 0);

    lv_obj_set_width(ui_comp_get_child(ui_Weather_Scrolldots_Scrolldots4, UI_COMP_PANEL_SCROLLDOTS_PANEL_D5), 8);
    lv_obj_set_height(ui_comp_get_child(ui_Weather_Scrolldots_Scrolldots4, UI_COMP_PANEL_SCROLLDOTS_PANEL_D5), 8);
    lv_obj_set_x(ui_comp_get_child(ui_Weather_Scrolldots_Scrolldots4, UI_COMP_PANEL_SCROLLDOTS_PANEL_D5), 41);
    lv_obj_set_y(ui_comp_get_child(ui_Weather_Scrolldots_Scrolldots4, UI_COMP_PANEL_SCROLLDOTS_PANEL_D5), 0);
    lv_obj_set_style_bg_color(ui_comp_get_child(ui_Weather_Scrolldots_Scrolldots4, UI_COMP_PANEL_SCROLLDOTS_PANEL_D5),
                              lv_color_hex(0x101C52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_Weather_Scrolldots_Scrolldots4, UI_COMP_PANEL_SCROLLDOTS_PANEL_D5), 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_add_event_cb(ui_Screen_Weather, ui_event_Screen_Weather, LV_EVENT_ALL, NULL);

}
