// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Smart_Gadget

#include "../ui.h"

void ui_Screen_Alarm_screen_init(void)
{
    ui_Screen_Alarm = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Alarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_Alarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Alarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Screen_Alarm, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_Screen_Alarm, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm_Panel_Alarm_container = lv_obj_create(ui_Screen_Alarm);
    lv_obj_set_width(ui_Alarm_Panel_Alarm_container, lv_pct(100));
    lv_obj_set_height(ui_Alarm_Panel_Alarm_container, lv_pct(100));
    lv_obj_set_align(ui_Alarm_Panel_Alarm_container, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Alarm_Panel_Alarm_container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Alarm_Panel_Alarm_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm_Small_Label_Set_alarm = ui_Label_Small_Label_create(ui_Alarm_Panel_Alarm_container);
    lv_obj_set_x(ui_Alarm_Small_Label_Set_alarm, 0);
    lv_obj_set_y(ui_Alarm_Small_Label_Set_alarm, 17);
    lv_obj_set_align(ui_Alarm_Small_Label_Set_alarm, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Alarm_Small_Label_Set_alarm, "Set alarm");
    lv_obj_set_style_text_color(ui_Alarm_Small_Label_Set_alarm, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Alarm_Small_Label_Set_alarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm_Alarm_Comp_Alarm_Comp = ui_Panel_Alarm_Comp_create(ui_Alarm_Panel_Alarm_container);
    lv_obj_set_x(ui_Alarm_Alarm_Comp_Alarm_Comp, 0);
    lv_obj_set_y(ui_Alarm_Alarm_Comp_Alarm_Comp, 43);





    ui_Alarm_Alarm_Comp_Alarm_Comp1 = ui_Panel_Alarm_Comp_create(ui_Alarm_Panel_Alarm_container);
    lv_obj_set_x(ui_Alarm_Alarm_Comp_Alarm_Comp1, 0);
    lv_obj_set_y(ui_Alarm_Alarm_Comp_Alarm_Comp1, 128);

    lv_label_set_text(ui_comp_get_child(ui_Alarm_Alarm_Comp_Alarm_Comp1, UI_COMP_PANEL_ALARM_COMP_LABEL_ALARM_NUM2),
                      "8:00");

    lv_label_set_text(ui_comp_get_child(ui_Alarm_Alarm_Comp_Alarm_Comp1, UI_COMP_PANEL_ALARM_COMP_SMALL_LABEL_PERIOD),
                      "Breakfast");

    lv_obj_add_state(ui_comp_get_child(ui_Alarm_Alarm_Comp_Alarm_Comp1, UI_COMP_PANEL_ALARM_COMP_SWITCH_SWITCH1),
                     LV_STATE_CHECKED);      /// States


    ui_Alarm_Alarm_Comp_Alarm_Comp2 = ui_Panel_Alarm_Comp_create(ui_Alarm_Panel_Alarm_container);
    lv_obj_set_x(ui_Alarm_Alarm_Comp_Alarm_Comp2, 0);
    lv_obj_set_y(ui_Alarm_Alarm_Comp_Alarm_Comp2, 213);

    lv_label_set_text(ui_comp_get_child(ui_Alarm_Alarm_Comp_Alarm_Comp2, UI_COMP_PANEL_ALARM_COMP_LABEL_ALARM_NUM2),
                      "9:30");

    lv_label_set_text(ui_comp_get_child(ui_Alarm_Alarm_Comp_Alarm_Comp2, UI_COMP_PANEL_ALARM_COMP_SMALL_LABEL_PERIOD),
                      "Yoga");



    ui_Alarm_Alarm_Comp_Alarm_Comp3 = ui_Panel_Alarm_Comp_create(ui_Alarm_Panel_Alarm_container);
    lv_obj_set_x(ui_Alarm_Alarm_Comp_Alarm_Comp3, 0);
    lv_obj_set_y(ui_Alarm_Alarm_Comp_Alarm_Comp3, 298);
    lv_obj_set_style_border_color(ui_Alarm_Alarm_Comp_Alarm_Comp3, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Alarm_Alarm_Comp_Alarm_Comp3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Alarm_Alarm_Comp_Alarm_Comp3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Alarm_Alarm_Comp_Alarm_Comp3, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_label_set_text(ui_comp_get_child(ui_Alarm_Alarm_Comp_Alarm_Comp3, UI_COMP_PANEL_ALARM_COMP_LABEL_ALARM_NUM2),
                      "11:00");

    lv_label_set_text(ui_comp_get_child(ui_Alarm_Alarm_Comp_Alarm_Comp3, UI_COMP_PANEL_ALARM_COMP_SMALL_LABEL_PERIOD),
                      "Sleep");



    ui_Alarm_Scrolldots_Scrolldots5 = ui_Panel_Scrolldots_create(ui_Screen_Alarm);
    lv_obj_set_x(ui_Alarm_Scrolldots_Scrolldots5, 0);
    lv_obj_set_y(ui_Alarm_Scrolldots_Scrolldots5, -8);

    lv_obj_set_width(ui_comp_get_child(ui_Alarm_Scrolldots_Scrolldots5, UI_COMP_PANEL_SCROLLDOTS_PANEL_D1), 4);
    lv_obj_set_height(ui_comp_get_child(ui_Alarm_Scrolldots_Scrolldots5, UI_COMP_PANEL_SCROLLDOTS_PANEL_D1), 4);

    lv_obj_set_x(ui_comp_get_child(ui_Alarm_Scrolldots_Scrolldots5, UI_COMP_PANEL_SCROLLDOTS_PANEL_D2), 10);
    lv_obj_set_y(ui_comp_get_child(ui_Alarm_Scrolldots_Scrolldots5, UI_COMP_PANEL_SCROLLDOTS_PANEL_D2), 0);

    lv_obj_set_x(ui_comp_get_child(ui_Alarm_Scrolldots_Scrolldots5, UI_COMP_PANEL_SCROLLDOTS_PANEL_D3), 20);
    lv_obj_set_y(ui_comp_get_child(ui_Alarm_Scrolldots_Scrolldots5, UI_COMP_PANEL_SCROLLDOTS_PANEL_D3), 0);

    lv_obj_set_x(ui_comp_get_child(ui_Alarm_Scrolldots_Scrolldots5, UI_COMP_PANEL_SCROLLDOTS_PANEL_D4), 30);
    lv_obj_set_y(ui_comp_get_child(ui_Alarm_Scrolldots_Scrolldots5, UI_COMP_PANEL_SCROLLDOTS_PANEL_D4), 0);

    lv_obj_set_x(ui_comp_get_child(ui_Alarm_Scrolldots_Scrolldots5, UI_COMP_PANEL_SCROLLDOTS_PANEL_D5), 40);
    lv_obj_set_y(ui_comp_get_child(ui_Alarm_Scrolldots_Scrolldots5, UI_COMP_PANEL_SCROLLDOTS_PANEL_D5), 0);

    lv_obj_set_width(ui_comp_get_child(ui_Alarm_Scrolldots_Scrolldots5, UI_COMP_PANEL_SCROLLDOTS_PANEL_D6), 8);
    lv_obj_set_height(ui_comp_get_child(ui_Alarm_Scrolldots_Scrolldots5, UI_COMP_PANEL_SCROLLDOTS_PANEL_D6), 8);
    lv_obj_set_x(ui_comp_get_child(ui_Alarm_Scrolldots_Scrolldots5, UI_COMP_PANEL_SCROLLDOTS_PANEL_D6), 50);
    lv_obj_set_y(ui_comp_get_child(ui_Alarm_Scrolldots_Scrolldots5, UI_COMP_PANEL_SCROLLDOTS_PANEL_D6), 0);
    lv_obj_set_style_bg_color(ui_comp_get_child(ui_Alarm_Scrolldots_Scrolldots5, UI_COMP_PANEL_SCROLLDOTS_PANEL_D6),
                              lv_color_hex(0x101C52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_Alarm_Scrolldots_Scrolldots5, UI_COMP_PANEL_SCROLLDOTS_PANEL_D6), 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen_Alarm, ui_event_Screen_Alarm, LV_EVENT_ALL, NULL);

}
