// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Smart_Gadget

#include "../ui.h"

void ui_Screen_Splash_screen_init(void)
{
    ui_Screen_Splash = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_Splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_Splash, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Splash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Splash_Small_Label_Demo = ui_Label_Small_Label_create(ui_Screen_Splash);
    lv_obj_set_x(ui_Splash_Small_Label_Demo, 0);
    lv_obj_set_y(ui_Splash_Small_Label_Demo, 75);
    lv_obj_set_align(ui_Splash_Small_Label_Demo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Splash_Small_Label_Demo, "Demo");
    lv_obj_set_style_text_color(ui_Splash_Small_Label_Demo, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Splash_Small_Label_Demo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Splash_Small_Label_Smart_Gadget = ui_Label_Small_Label_create(ui_Screen_Splash);
    lv_obj_set_x(ui_Splash_Small_Label_Smart_Gadget, 0);
    lv_obj_set_y(ui_Splash_Small_Label_Smart_Gadget, 50);
    lv_obj_set_align(ui_Splash_Small_Label_Smart_Gadget, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Splash_Small_Label_Smart_Gadget, "Smart Gadget");
    lv_obj_set_style_text_color(ui_Splash_Small_Label_Smart_Gadget, lv_color_hex(0x000746),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Splash_Small_Label_Smart_Gadget, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Splash_Image_SLS_Logo = lv_image_create(ui_Screen_Splash);
    lv_image_set_src(ui_Splash_Image_SLS_Logo, &ui_img_sls_logo_png);
    lv_obj_set_width(ui_Splash_Image_SLS_Logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Splash_Image_SLS_Logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Splash_Image_SLS_Logo, 0);
    lv_obj_set_y(ui_Splash_Image_SLS_Logo, -50);
    lv_obj_set_align(ui_Splash_Image_SLS_Logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Splash_Image_SLS_Logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Splash_Image_SLS_Logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen_Splash, ui_event_Screen_Splash, LV_EVENT_ALL, NULL);

}
