esp_toml_version = 1.0
firmware_images_url = "https://espressif.github.io/esp-brookesia/"

supported_apps = ["FACTORY_ECHOEAR_SPEAKER_IDF_v5"]

[FACTORY_ECHOEAR_SPEAKER_IDF_v5]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "factory_echoear_speaker_esp32s3_release_v5_5.bin"
android_app_url = ""
ios_app_url = ""
